on: push

jobs: 
    assembleRelease:
        
        runs-on: ubuntu-latest
        
        steps:
        -   uses: actions/checkout@v2
        -   name: restoreKeystorerun
            run: |
                echo "${{ secrets.KEYSTORE }}" > keystore.jks.asc
                gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch keystore.jks.asc > release.keystore
                ls
                cat release.keystore
